format = """\
[╭╴](fg:arrow)$username$git_branch$directory$cmd_duration\
$python$conda$nodejs
[╰─](fg:arrow)$character\
"""

add_newline = true
palette = "normal"

[palettes.normal]
arrow = "#FBFBFB"
os = "#16f4d0"
os_admin = "#e4ff1a"
directory = "#9ffff5"
time = "#bdfffd"
node = "#a5e6ba"
git = "#f17f29"
git_status = "#DFEBED"
python = "#edf67d"
conda = "#70e000"
java = "#861215"
rust = "#C33C00"
clang = "#00599D"
duration = "#ce4257"
text_color = "#EDF2F4"
text_light = "#26272A"

[username]
style_user = 'bold os'
style_root = 'bold os_admin'
format = '[  $user](fg:$style) '
disabled = false
show_always = true

[character]
success_symbol = "[󰍟](fg:arrow)"
error_symbol = "[󰍟](fg:red)"

[directory]
format = "at [$path](bold $style)[$read_only]($read_only_style) "
truncation_length = 2
style = "fg:directory"
read_only_style = "fg:directory"
before_repo_root_style = "fg:directory"
truncation_symbol = "…/"
truncate_to_repo = true
read_only ="  "

[time]
disabled = true
format = "at [󱑈 $time]($style)"
time_format = "%H:%M"
style = "bold fg:time"

[cmd_duration]
format = "took [ $duration]($style)"
style = "bold fg:duration"
min_time = 500

[git_branch]
format = "via [$symbol$branch]($style) "
style = "bold fg:git"
symbol = " "

[git_status]
format = '[ $all_status$ahead_behind ]($style)'
style = "fg:text_color bg:git"
disabled = true

[docker_context]
disabled=true
symbol = " "

[package]
disabled=true

[nodejs]
format = "via [ $symbol$version ]($style)"
style = "bg:node fg:text_light"
symbol = "󰎙 "
version_format = "${raw}"
disabled=false

[python]
disabled=false
format = 'via [ ${symbol}${pyenv_prefix}(${version})( \($virtualenv\)) ]($style)'
symbol = " "
version_format = "${raw}"
style = "bg:python fg:text_light"

[conda]
format = "[ $symbol$environment ]($style) "
style = "bg:conda fg:text_light"
ignore_base = false
disabled=false
symbol = " "

[java]
format = "[$symbol$version](bg:java )"
version_format = "${raw}"
symbol = " "
disabled = true

[c]
format = "[$symbol($version(-$name) )](bg:clang )"
symbol = " "
version_format = "${raw}"
disabled=true

[rust]
format = "(fg:rust)[$symbol$version](bg:rust )"
symbol = " "
version_format = "${raw}"
disabled=true

[os.symbols]
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Gentoo = " "
Linux = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
openSUSE = " "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = " "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = " "